global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["192.168.0.107:9090"]

  - job_name: "ubuntu-servers"
    static_configs:
      - targets:
          - 192.168.0.105:9100

  - job_name: "windows-servers"
    static_configs:
     - targets:
         - 192.168.0.104:9182  
#         - 192.168.0.104:9182 
#
#  - job_name: "prod-servers"
#   ec2_sd_configs:
#    - port: 9100
#      filters:
#        - name  : tag:Environment
#          values: ["prod"]
#
#  - job_name: "dev-servers"
#    ec2_sd_configs:
#    - port: 9100
#      filters:
#        - name  : tag:Environment
#          values: ["dev"]
